services:
  scipy-light:
    # build:
      # context: ./scipy-light
      # dockerfile: Dockerfile
    image: qsyao215/scipy_light
    # command: ["tail", "-f", "/dev/null"]
    command: ["fastmcp", "run", "ipython_server.py:mcp", "--transport", "http", "--host", "0.0.0.0", "--port", "${SCIPY_LIGHT_PORT:-8000}"]
    container_name: scipy-light
    volumes:
      - ./scipy-light/ipython_server.py:/root/ipython_server.py
    ports:
      - "${SCIPY_LIGHT_PORT:-8000}:${SCIPY_LIGHT_PORT:-8000}"

  vienna_academic:
    # build:
      # context: ./app
      # dockerfile: Dockerfile
    image: qsyao215/vienna_academic
    # command: ["tail", "-f", "/dev/null"]
    command: ["fastapi", "run", "server.py", "--port", "${VIENNA_ACADEMIC_PORT:-8001}"]
    container_name: vienna_academic
    environment:
      - SCIPY_LIGHT_PORT=${SCIPY_LIGHT_PORT:-8000}
      - SILICONFLOW_BASE_URL=${SILICONFLOW_BASE_URL}
      - SILICONFLOW_API_KEY=${SILICONFLOW_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    volumes:
      - ./app:/root
    depends_on:
      - scipy-light
    ports:
      - "${VIENNA_ACADEMIC_PORT:-8001}:${VIENNA_ACADEMIC_PORT:-8001}"
