services:
  scipy-light:
    build: ./scipy-light
    image: scipy-light
    container_name: scipy-light
    networks:
      - vienna_net

  vienna_gpu:
    build: ./app
    image: vienna_gpu
    container_name: vienna_gpu
    volumes:
      - ./:/root/ViennaAcademic
      - ./marker:/root/.cache/datalab
      - //var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres
      - scipy-light
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - vienna_net
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: vienna_academic
      POSTGRES_PASSWORD: vienna_academic
      POSTGRES_DB: vadb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vienna_net

networks:
  vienna_net:
    driver: bridge

volumes:
  postgres_data:
