[package]
name = "va_rust_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "va_rust_utils"
crate-type = ["cdylib"]

[dependencies]
base64 = "0.22.1"
pyo3 = "0.25.0"
regex = "1.11.1"

[lints.clippy]
pedantic = "warn"
nursery = "warn"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic= "abort"
strip = "symbols"
debug = false

[profile.dev]
opt-level = 3
lto = "fat"
codegen-units = 1
panic= "abort"
strip = "symbols"
debug = false
